Initialize node-express
Levitators/JavaScript-Starter-Kit pull request #1
Opened 2017-11-17 20:27 UTC by thearavind

2017-11-18 07:50 UTC, ravi-lattis commented on node-express/.eslintrc.js
> +};
Leave a new line at the end pls.

2017-11-18 07:51 UTC, ravi-lattis commented on node-express/Dockerfile
> +CMD [ "npm", "start" ]
Leave a new line at the end pls.

2017-11-18 07:52 UTC, ravi-lattis commented on node-express/README.md
> +Navigate to the project folder ane build the docker image using the below command
Pls, correct the spelling for `ane` to `and`.

2017-11-18 07:54 UTC, ravi-lattis commented on node-express/database/mongo.js
> +    _db = await MongoClient.connect(`mongodb://root:root@ds259865.mlab.com:59865/users`)
Get the database configuration from a central config file in the project.

2017-11-18 07:57 UTC, ravi-lattis commented on node-express/database/mongo.js
> +    connectToDB: connectToDB (),
There's a space came by mistake, I guess.

2017-11-18 07:58 UTC, ravi-lattis commented on node-express/database/mysql.js
> +            host: 'localhost',
Get all the database configuration from a central config file.

2017-11-18 07:59 UTC, ravi-lattis commented on node-express/package.json
> +  "author": "Aravindhan (thearuvi@gmail.com)",
Please change the author to `Levitators`.

2017-11-18 08:14 UTC, ravirajsubramanian requested changes

2017-11-18 08:14 UTC, ravirajthedeveloper commented on node-express/.eslintrc.js
> +};
Please leave an empty line at the bottom.

2017-11-18 08:14 UTC, ravirajthedeveloper commented on node-express/Dockerfile
> +CMD [ "npm", "start" ]
Please leave an empty line at the bottom.

2017-11-18 08:14 UTC, ravirajthedeveloper commented on node-express/README.md
> +Navigate to the project folder ane build the docker image using the below command
Correct the spelling for `ane` to `and`.

2017-11-18 08:14 UTC, ravirajthedeveloper commented on node-express/database/mongo.js
> +    _db = await MongoClient.connect(`mongodb://root:root@ds259865.mlab.com:59865/users`)
Get all the database configuration details from a central config file.

2017-11-18 08:14 UTC, ravirajthedeveloper commented on node-express/database/mongo.js
> +    connectToDB: connectToDB (),
There's a space came by mistake, I guess.

2017-11-18 08:14 UTC, ravirajthedeveloper commented on node-express/database/pgsql.js
> +        _pg = pgp(`postgres://birlcvav:19QZsLOLiARafPCZOatrZobWlRYF5XGL@qdjjtnkv.db.elephantsql.com:5432/birlcvav`);
Get all the database configuration details from a central config file. Also, Do not expose your personal database configurations.

2017-11-18 08:14 UTC, ravirajthedeveloper commented on node-express/index.js
> +    let port = process.env.PORT || 3000
port can be `const`.

2017-11-18 08:14 UTC, ravirajthedeveloper commented on node-express/package.json
> +  "author": "Aravindhan (thearuvi@gmail.com)",
Please change the author to `Levitators`.

2017-12-07 01:36 UTC, ravi-lattis approved these changes

2017-12-07 01:45 UTC, ravirajsubramanian approved these changes

2017-12-07 01:46 UTC, merged